name: shopsmart_admin_ar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State management
  provider: ^6.0.5
  # Local Memory
  shared_preferences: ^2.1.0
  # Icons
  flutter_iconly: ^1.0.2
  ionicons: ^0.2.2
  # UI
  shimmer: ^2.0.0
  fancy_shimmer_image: ^2.0.2
  dynamic_height_grid_view: ^0.0.3
  card_swiper: ^2.0.4
  image_picker: ^0.8.7+5
  top_snackbar_flutter: ^3.1.0
  # Utils
  uuid: ^3.0.7
  # firebase
  firebase_core: ^2.29.0
  cloud_firestore: ^4.16.1
  firebase_storage: ^11.7.1

dev_dependencies:
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/dashboard/
    
flutter_native_splash:
  color: "#ffffff"
  image: assets/lightSplash.png  
  color_dark: "#28222C"
  image_dark: assets/darkSplash.png

  android_12:
    image: assets/lightSplash.png
    icon_background_color: "#ffffff"
    image_dark: assets/darkSplash.png
    icon_background_color_dark: "#28222C"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/shopping_cart.png"
  min_sdk_android: 17 