// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfNHyKPQUGTgN-P2cZXe7XI0vNJNs255g',
    appId: '1:523979426975:web:0a7f1a533ade26ba6ae6aa',
    messagingSenderId: '523979426975',
    projectId: 'storeshop-b3b95',
    authDomain: 'storeshop-b3b95.firebaseapp.com',
    storageBucket: 'storeshop-b3b95.appspot.com',
    measurementId: 'G-MJT4ZFPNFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1l1Ve0lEO8RrjRszmINbKOWJf86yZqJY',
    appId: '1:523979426975:android:79cab754a45b2d286ae6aa',
    messagingSenderId: '523979426975',
    projectId: 'storeshop-b3b95',
    storageBucket: 'storeshop-b3b95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8WVy7G9kElrNpaTJGV6-b76R80betvn8',
    appId: '1:523979426975:ios:ef0bef98f845a73a6ae6aa',
    messagingSenderId: '523979426975',
    projectId: 'storeshop-b3b95',
    storageBucket: 'storeshop-b3b95.appspot.com',
    iosBundleId: 'com.example.shopsmartadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8WVy7G9kElrNpaTJGV6-b76R80betvn8',
    appId: '1:523979426975:ios:ef0bef98f845a73a6ae6aa',
    messagingSenderId: '523979426975',
    projectId: 'storeshop-b3b95',
    storageBucket: 'storeshop-b3b95.appspot.com',
    iosBundleId: 'com.example.shopsmartadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfNHyKPQUGTgN-P2cZXe7XI0vNJNs255g',
    appId: '1:523979426975:web:9a1e82e66178eec36ae6aa',
    messagingSenderId: '523979426975',
    projectId: 'storeshop-b3b95',
    authDomain: 'storeshop-b3b95.firebaseapp.com',
    storageBucket: 'storeshop-b3b95.appspot.com',
    measurementId: 'G-NC4PMFX1L5',
  );
}
